### ISSUE TITLE
请问如何删除曾经上传过的app？

### ISSUE THREAD

**Issue by exrock** [iineva/ipa-server#10]
请问如何安全删除曾经上传过的app？

**Comment by iineva** [comment]
没有开发此功能，把需要删除的链接发给我，我帮你删除

发自我的 iPhone

**Comment by exrock** [comment]
谢谢，我是将ipa-server跑在了自己的vps上，是手工删除‘/app/upload’目录下对应的app目录和json数据吗？

**Comment by exrock** [comment]
明白了 THS
