### ISSUE TITLE
Can not finish install ERROR

### ISSUE THREAD

**Issue by tomlinly** [iineva/ipa-server#11]
Step 6/9 : RUN npm install --production --registry=https://registry.npm.taobao.org
 ---> Running in a1771b815d9f
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info lifecycle ipa-server@1.0.0~preinstall: ipa-server@1.0.0
npm WARN ipa-server@1.0.0 No description
npm WARN ipa-server@1.0.0 No repository field.

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npm.taobao.org/bplist-parser failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-24T03_13_12_320Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install --production --registry=https://registry.npm.taobao.org' returned a non-zero code: 1

before i installed,but today show this.
Thank you.

**Comment by iineva** [comment]
remove `node_modules/` and retry.
