### ISSUE TITLE
在centos 7上安装错误

### ISSUE THREAD

**Issue by Larryliuy** [iineva/ipa-server#12]
![image](https://user-images.githubusercontent.com/10302100/49695695-fadc0b80-fbd9-11e8-8b8e-83b4cb081a10.png)

**Comment by iineva** [comment]
看提示似乎是无文件写入权限，推荐用docker方式安装，没这么多问题

发自我的 iPhone

**Comment by Larryliuy** [comment]
> 看提示似乎是无文件写入权限，推荐用docker方式安装，没这么多问题 发自我的 iPhone
> […](#)
> 在 2018年12月9日，17:43，Larryliuy ***@***.***> 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

报错是没有权限，有个疑问就是为啥会需要创建文件到node文件的lib目录，创建到其他目录不行吗？

**Comment by Larryliuy** [comment]
![image](https://user-images.githubusercontent.com/10302100/49695976-b94d5f80-fbdd-11e8-9a45-2b9ae1592906.png)

**Comment by iineva** [comment]
某个依赖库的安装脚本创建的文件

发自我的 iPhone

**Comment by Larryliuy** [comment]
好的，谢谢，我还是用docker安装吧
