### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by likaijie111** [iineva/ipa-server#17]
[root@izbkrynu8btkjbz ipa-server]# docker-compose up -d
Building web
Step 1/9 : FROM node:8.4.0
 ---> 386940f92d24
Step 2/9 : MAINTAINER Steven <s@beeeye.cn>
 ---> Using cache
 ---> 4a550686d500
Step 3/9 : WORKDIR /app
 ---> Using cache
 ---> 43644256975f
Step 4/9 : COPY package.json .
 ---> Using cache
 ---> 0b27fa5519fd
Step 5/9 : COPY package-lock.json .
 ---> Using cache
 ---> 4d18bd6e590e
Step 6/9 : RUN npm install --production --registry=https://registry.npm.taobao.org
 ---> Running in 755ad06acffb

container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""
ERROR: Service 'web' failed to build: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""

**Comment by iineva** [comment]
try this image, and this image is use github actions to build, you can check build script on `.github/workflows/docker-build.yml`
```
docker pull ineva/ipa-server:latest
```
