### ISSUE TITLE
您好。我安装的时候只在手机上显示一个灰色的图标 下面写着等待中，但是并没有下载进度

### ISSUE THREAD

**Issue by kuaile1993** [iineva/ipa-server#23]
您好。我安装的时候只在手机上显示一个灰色的图标 下面写着等待中，但是并没有下载进度，好像卡在这里了，不能安装。是什么原因呢？

**Comment by kuaile1993** [comment]
![1](https://user-images.githubusercontent.com/52553619/71321773-62b97780-24f9-11ea-8b01-f31b8fc3b801.jpg)

**Comment by iineva** [comment]
先确认https是否已成功开启，再确认ipa是否正确签名，如果上面两步都没问题，重启手机或者换台手机试试，iPhone偶尔会出现安装不了的情况

发自我的iPhone

**Comment by kuaile1993** [comment]
好的，等了很久以后，终于开始下载 了，上传速度和下载速度都很慢，已经快半个小时了，才下了十分之一不到， 
目前不清楚是不是服务器的原因，感觉速度慢的有点离谱了。另外，非常喜欢您的这个项目，真诚的说句谢谢

**Comment by iineva** [comment]
慢的话八成是网络问题，检查服务器带宽和手机4G或者wifi

发自我的iPhone

**Comment by kuaile1993** [comment]
您能看看在您那里能下吗？https://ipa2.javanx.com

**Comment by iineva** [comment]
试过了，你那边服务器带宽太小了下载速度只有几十K。看了ip你那边用的是阿里云，目测你那边用的是1M固定带宽，如果测试用，建议改成50M带宽按量收费，流量费应该是0.8元1G
如果你的目的是线上分发，现在这个项目还没做CDN分发，如果用户规模大流量费用会高一些

发自我的iPhone

**Comment by kuaile1993** [comment]
好的  非常感谢

**Comment by kuaile1993** [comment]
您好，我下载完后  提示无法安装XXX，请稍后再试

**Comment by iineva** [comment]
提示无法安装，如果确认网络没问题，就是签名不正确
