### ISSUE TITLE
测试的https://ipa.ineva.cn无法访问

### ISSUE THREAD

**Issue by BeanYD** [iineva/ipa-server#26]

**Comment by iineva** [comment]
域名备案失效了还没时间处理，需要用的话自己部署吧

**Comment by iineva** [comment]
不再提供测试地址，需要试用可以自行一键部署到Heroku

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/iineva/ipa-server)
