### ISSUE TITLE
how to remove an app ???

### ISSUE THREAD

**Issue by vinchouros** [iineva/ipa-server#29]
Congrat! Good job. Just how to remove an app ??? pls

**Comment by iineva** [comment]
now, we can delete app from app info page.
use branch `main` or release `v1.1` to try this new function.

**Comment by vinchouros** [comment]
Thank you are the boss. I don't know how to upadate into a docker ?

**Comment by iineva** [comment]
'''
docker pull ineva/ipa-server:latest
docker-compose restart
'''

**Comment by iineva** [comment]
or change
image: ineva/ipa-server:latest
to
image: ineva/ipa-server:v1.1
than
docker-compose up -d

**Comment by vinchouros** [comment]
i try but it's the same. I try to delete all and reinstall but same. I don't know why

**Comment by vinchouros** [comment]
it's WORKING!!!! Thank bro!
