### ISSUE TITLE
安装时出现报错。

### ISSUE THREAD

**Issue by foxes1998** [iineva/ipa-server#5]
> pngdefry@1.1.6 postinstall /app/node_modules/pngdefry
> node postinstall.js

(node:26) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm info lifecycle randomstring@1.1.5~postinstall: randomstring@1.1.5
npm info lifecycle simple-plist@0.2.1~postinstall: simple-plist@0.2.1
npm info linkStuff ipa-server@1.0.0
npm info lifecycle ipa-server@1.0.0~install: ipa-server@1.0.0
npm info lifecycle ipa-server@1.0.0~postinstall: ipa-server@1.0.0
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN ipa-server@1.0.0 No description
npm WARN ipa-server@1.0.0 No repository field.

added 93 packages in 7.263s
npm info ok 
 ---> 8df0a5753a0d
Removing intermediate container 728d7b71d4cd
Step 7/9 : COPY . .

另外访问https://domain:9008/无响应(ERR_CONNECTION_CLOSED)
不加端口也如此
访问http://domain:9008/正常

环境debian9（docker-compose version 1.8.0, build unknown）
（小白一个，使用的替换过的 docker-compose.yml

**Comment by iineva** [comment]
请访问：https://domain
不需要指定端口号

**Comment by nobut** [comment]
安装测试没问题,就是修改完docker-compose,访问https://ip 无法连接.访问http://ip:9008能访问,请问这是啥问题啊?

**Comment by iineva** [comment]
HTTPs必须用域名，不能用IP

**Comment by nobut** [comment]
好了,谢谢,再请教您一下,在手机上下载特慢和我的带宽有关系吗?

**Comment by iineva** [comment]
先搞清楚https和反向代理是怎么回事就能理解怎么回事了

**Comment by garymaxallen** [comment]
> HTTPs必须用域名，不能用IP

域名还必须是经过认证的域名？我随便用了一个本地域名，也不能安装。

这就一下子提高了私人部署server的门槛，你首先得有个域名。
