### ISSUE TITLE
ERROR at runnning "docker-compose up -d"

### ISSUE THREAD

**Issue by Chen-kaiyuan** [iineva/ipa-server#6]
Hi ,I git code with centos 7 and running command after install  python-pip and docker-compose.
But， running "docker-compose up -d"  occurred has error.
This is  running steps 
1. git clone https://github.com/iineva/ipa-server
2. cd ipa-server
3. yum -y install python-pip
4. pip install docker-compose
5. docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

please help me！ Thanks ！

**Comment by iineva** [comment]
Your docker daemon is down. Try reinstall docker.

发自我的 iPhone

**Comment by iineva** [comment]
Do you installed docker daemon?

发自我的 iPhone
