### ISSUE TITLE
上传ipa包会导致oom,upload,OOM

### ISSUE THREAD

**Issue by luobote** [iineva/ipa-server#64]
./ipasd &
ts="2024-11-19 11:56:31.636" caller=ipasd.go:152 msg="SERVER LISTEN ON: http://0.0.0.0:8080"
ts="2024-11-19 11:56:34.191" caller=level.go:63 level=info modle=/api/list status=start request="{publicURL:https://ios.xxxx.com id:}"
ts="2024-11-19 11:56:34.191" caller=level.go:63 level=info modle=/api/list status=done took=83.204µs
ts="2024-11-19 11:58:23.567" caller=level.go:63 level=info modle=/api/upload status=start request={file:0xc000298b10}

[1]+  Killed                  ./ipasd

#messages-log

Nov 19 11:45:33 localhost kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=ipasd,pid=28204,uid=0
Nov 19 11:45:33 localhost kernel: Out of memory: Killed process 28204 (ipasd) total-vm:66418376kB, anon-rss:15113292kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:42796kB oom_score_adj:0

**Comment by luobote** [comment]
[https://github.com/iineva/ipa-server/issues/56](url) 按照这个说法，我使用性能更高的服务器也会导致OOM

Nov 19 12:26:05 server001 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0-1,global_oom,task_memcg=/,task=ipasd,pid=9180,uid=0
Nov 19 12:26:05 server001 kernel: Out of memory: Killed process 9180 (ipasd) total-vm:484403976kB, anon-rss:95997000kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:255988kB oom_score_adj:0

**Comment by luobote** [comment]
> 你的服务器什么配置，上传包体有多大？是apk还是ipa包？如果方便的话可以发个样本到我的邮箱给我调试
回复：sorry，我们是内部包不方便对外，不过可以下载游戏类的ipa版本包测试。

服务器配置：
CPU：64核  内存：96G  SSD: 2TB

ipa测试：
包体容量：3.5GB
故障描述：内存暴增，系统日志显示ipasd进程OOM

apk测试：
包体容量：1.5GB
故障描述：正常识别，没有故障

**Comment by iineva** [comment]
要解决这个问题需要修改上传包的处理流程，我有空的时候会做更新

**Comment by iineva** [comment]
try 2.5.1
